---
sudo: required

language: python
python:
  - "2.7"

services:
  - docker

cache:
  directories:
    - vendor/bundle
    - $HOME/.cache/pip
    - $HOME/.local
    - roles

jobs:
  include:
    - stage: Spec
      name: Trusty
      env: ANSIBLE_VERSION="2.7" ENVIRONMENT_NAME=trusty
      script: bundle exec rake spec:$ENVIRONMENT_NAME

before_install:
  - docker pull ubuntu:${ENVIRONMENT_NAME}

  - travis_retry bundle install --deployment

install:
  - travis_retry pip install -U ansible==${ANSIBLE_VERSION}.*

  - travis_retry ansible-galaxy install -r roles.yml

  - travis_wait bundle exec rake environment:${ENVIRONMENT_NAME}:provision

after_script:
  - bundle exec rake environment:destroy

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
