---
- hosts: all
  remote_user: root
  become: yes

  vars:
    site_type: python
    domain: test.dev
  vars_files:
    - defaults/main.yml
  roles:
    - bbatsche.Nginx
  tasks:
    - include: tasks/main.yml
