---
- hosts: all
  remote_user: root
  become: yes

  vars:
    domain: test.dev

  vars_files:
    - defaults/main.yml

  roles:
    - role: bbatsche.Base
    - role: bbatsche.Nginx
      site_type: python

  tasks:
    - include: tasks/main.yml
