---
- debug: var=ansible_distribution_release
- debug: var=python_version

- name: Verify Distro and Python Version
  assert:
    that: not (ansible_distribution_release == "trusty" and (python_version == 2 or python_version == "2"))
    msg: This role no longer supports Python 2 in Ubuntu 14.04 Trusty

- name: Install Python
  apt:
    name:
      - python
      - python-dev
      - python-pip
      - python3
      - python3-dev
      - python3-pip
    state: present
  become: yes

- name: Upgrade Pip
  pip: name=pip executable={{ item }} state=latest
  become: yes
  loop:
    - pip3
    - pip2

- name: Install Virtualenv and Virtualenvwrapper
  pip:
    name:
      - virtualenv
      - virtualenvwrapper
    executable: "{{ item }}"
  become: yes
  loop:
    - pip2
    - pip3

- name: Source Virtualenv Wrapper to Shell
  file:
    state: link
    src: /usr/local/bin/virtualenvwrapper.sh
    dest: /etc/profile.d/virtualenvwrapper.sh
  become: yes

- name: WSGI Environment Setting for CLI
  lineinfile:
    dest: ~/.bashrc
    regexp: ^\s*export\s+WSGI_ENV=
    line: 'export WSGI_ENV="development"'
    insertafter: EOF
    state: present
  when: env_name == "dev"

- name: Copy Nginx Config
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/python-{{ domain }}.conf
  become: yes
  when: domain is defined
  notify:
    - Restart Nginx
    - Restart Passenger App

- name: Copy Passenger WSGI Stub
  template:
    src: passenger_wsgi.py.j2
    dest: "{{ http_root }}/{{ domain }}/passenger_wsgi.py"
  when: copy_wsgi
  notify: Restart Passenger App
