---
- name: Install Python
  apt: package={{ item }} state=present
  become: yes
  with_items:
    - python
    - python-dev
    - python-pip
    - python3
    - python3-dev
    - python3-pip

- name: Upgrade Pip
  pip: name=pip executable={{ item }} state=latest
  become: yes
  with_items:
    - pip2
    # - pip3

- name: Install Virtualenv
  pip: name=virtualenv executable={{ item }}
  become: yes
  with_items:
    - pip2
    - pip3

- name: Install Virtualenv Wrapper
  pip: name=virtualenvwrapper executable={{ item }}
  become: yes
  with_items:
    - pip2
    - pip3

- name: Source Virtualenv Wrapper to Shell
  file:
    state: link
    src: /usr/local/bin/virtualenvwrapper_lazy.sh
    dest: /etc/profile.d/virtualenvwrapper.sh
  become: yes

- name: WSGI Environment Setting for CLI
  lineinfile:
    dest: ~/.bashrc
    regexp: ^\s*export\s+WSGI_ENV=
    line: 'export WSGI_ENV="development"'
    insertafter: EOF
    state: present
  when: env_name == "dev"

- name: Copy Passenger WSGI Stub
  template:
    src: passenger_wsgi.py.j2
    dest: "{{ http_root }}/{{ domain }}/passenger_wsgi.py"
  when: copy_wsgi
  notify: Restart Passenger App
