---
- name: Install Python
  apt:
    name: "{{ python_packages }}"
    state: present
  become: yes

- name: Upgrade Pip
  pip:
    name: [setuptools, pip]
    executable: pip3
    state: latest
  become: yes

- name: Install Virtualenv and Virtualenvwrapper
  pip:
    name:
      - virtualenv
      - virtualenvwrapper
    executable: pip3
    extra_args: --ignore-installed
  become: yes

- name: Source Virtualenv Wrapper to Shell
  file:
    state: link
    src: /usr/local/bin/virtualenvwrapper.sh
    dest: /etc/profile.d/virtualenvwrapper.sh
  become: yes

- name: WSGI Environment Setting for CLI
  lineinfile:
    dest: ~/.bashrc
    regexp: ^\s*export\s+WSGI_ENV=
    line: 'export WSGI_ENV="development"'
    insertafter: EOF
    state: present
  when: env_name == "dev"

- name: Copy Nginx Config
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/python-{{ domain }}.conf
  become: yes
  when: domain is defined
  notify:
    - Restart Nginx
    - Restart Passenger App

- name: Copy Passenger WSGI Stub
  template:
    src: passenger_wsgi.py.j2
    dest: "{{ http_root }}/{{ domain }}/passenger_wsgi.py"
  when: copy_wsgi
  notify: Restart Passenger App
