---
- hosts: all

  vars:
    domain: python.test

  vars_files:
    - ../../defaults/main.yml
    - ../../vars/main.yml

  roles:
    - role: bbatsche.Nginx
      passenger_app: yes

  tasks:
    - include: ../../tasks/main.yml

  post_tasks:
    # Ansible's service module doesn't play well with Docker, so for testing just manually restart
    - name: Force Nginx Restart
      command: service nginx restart warn=no
      become: yes
      when: ansible_connection | default('smart') == 'docker'

    - name: Force Passenger App Restart
      command: passenger-config restart-app {{ http_root }}/{{ domain }} --ignore-app-not-running
      when: ansible_connection | default('smart') == 'docker'

    - name: Create Python Virutalenv
      command: virtualenv {{ http_root }}/{{ domain }}/env -p python3
      when: env_name != "dev"
